baseURL = "https://linnertmedia.de"
languageCode = "de-de"
title = "LinnertMedia"
pygmentsUseClasses = true
preserveTaxonomyNames = true
enableEmoji = true

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
tag = "tags"

[author]
name = "Andreas Linnert"

[outputs]
page = ["HTML"]
home = ["HTML"]
section = ["HTML", "RSS"]
taxonomyTerm = ["HTML"]
taxonomy = ["HTML", "RSS"]